from riglib.lint_policy import anti_slop_required, render_oxlint_config, resolve_rule_severities, rule_policy_summary


def test_default_policy_uses_audited_severities():
    rules = resolve_rule_severities()
    assert rules["anti-slop/no-chained-type-assertions"] == "error"
    assert rules["anti-slop/no-reflect-get"] == "warn"
    assert rules["anti-slop/no-runtime-typeof"] == "off"
    assert rules["typescript/no-unsafe-type-assertion"] == "error"
    assert rule_policy_summary() == {"error": 12, "warn": 4, "off": 3}


def test_all_true_really_enables_every_known_rule():
    rules = resolve_rule_severities({"all": True})
    assert set(rules.values()) == {"error"}


def test_disable_and_explicit_severity_win_after_all():
    rules = resolve_rule_severities(
        {
            "all": True,
            "disable": ["anti-slop/no-module-mocking"],
            "severity": {
                "anti-slop/no-reflect-get": "warn",
                "anti-slop/no-runtime-typeof": "off",
            },
        }
    )
    assert rules["anti-slop/no-module-mocking"] == "off"
    assert rules["anti-slop/no-reflect-get"] == "warn"
    assert rules["anti-slop/no-runtime-typeof"] == "off"


def test_group_can_be_disabled_and_rule_force_enabled():
    rules = resolve_rule_severities(
        {
            "groups": {"anti-slop": False},
            "enable": ["anti-slop/no-runtime-typeof"],
        }
    )
    assert rules["anti-slop/no-chained-type-assertions"] == "off"
    assert rules["anti-slop/no-runtime-typeof"] == "warn"
    assert rules["typescript/no-unsafe-type-assertion"] == "error"


def test_rendered_config_is_deterministic_and_registers_provider_when_needed():
    content = render_oxlint_config()
    assert content.startswith('import { defineConfig } from "oxlint";')
    assert "Generated by Rig" in content
    assert 'name: "anti-slop"' in content
    assert '"anti-slop/no-runtime-typeof": "off"' in content
    assert '"typescript/no-unsafe-type-assertion": "error"' in content


def test_provider_can_disappear_when_anti_slop_group_is_off():
    rules = resolve_rule_severities({"groups": {"anti-slop": False}})
    assert not anti_slop_required(rules)
    assert 'name: "anti-slop"' not in render_oxlint_config({"groups": {"anti-slop": False}})
