"""omp guard extension codegen — renders the permissions rule registry into a TS hook.

omp auto-discovers TS files under ``<agent root>/extensions/``; a ``tool_call`` handler
returning ``{block: true, reason}`` blocks a bash call BEFORE execution (verified live,
rig-cli#202). This module turns :data:`riglib.permissions.OMP_GUARD_DENY_RULES` /
:data:`OMP_GUARD_ASK_RULES` into the wholly rig-owned ``rig-permissions-guard.ts`` — ONE
registry, ONE renderer, never a hand-copied second list.

The generated file carries a machine-parseable provenance header (template version, rule
ids, sha256 of the rule payload) so drift/deprovision can tell a rig-generated file from a
foreign one, and a runtime event-shape self-check that fails CLOSED with a loud
``rig-permissions-guard.incompatible`` marker if omp ever renames the ``toolName`` /
``input.command`` contract (a silent no-op after an upgrade is the worst outcome).

RESIDUAL fail-open mode (documented, Phase-2): if omp stops LOADING the extension at all
(discovery removed, load-time failure), no handler ever runs — the self-check and heartbeat
cannot fire, drift sees byte-identical files, and the approval posture stays relaxed with
zero enforcement. The opt-in activation probe (:mod:`riglib.omp_probe`) is the Phase-1
detection for this; a passive session-heartbeat check is the planned Phase-2 complement.

Stdlib-only at import time (the repo import rule).
"""

from __future__ import annotations

import dataclasses
import hashlib
import json

from .permissions import (
    OMP_GUARD_ASK_RULES,
    OMP_GUARD_DENY_RULES,
    GuardRule,
)

#: bump when the generated TS SHAPE changes (not the rules — those flip the rules hash).
GUARD_TEMPLATE_VERSION = 1

#: written next to the extension by the GUARD ITSELF when the omp event contract breaks;
#: drift surfaces its existence (the guard blocks all bash in that state — fail closed).
INCOMPATIBLE_MARKER_NAME = "rig-permissions-guard.incompatible"

_PROVENANCE_PREFIX = "// rig-guard-provenance: "


def _rules_payload(deny: tuple[GuardRule, ...], ask: tuple[GuardRule, ...]) -> str:
    """The canonical JSON the provenance hash is computed over (stable key order)."""
    return json.dumps(
        {
            "deny": [dataclasses.asdict(r) for r in deny],
            "ask": [dataclasses.asdict(r) for r in ask],
        },
        sort_keys=True,
        separators=(",", ":"),
    )


def _rules_ts(rules: tuple[GuardRule, ...]) -> str:
    """One generated ``{ id, hint, matcher, tokens, flags }`` entry per line."""
    lines = []
    for r in rules:
        tokens = json.dumps(list(r.tokens))
        flags = json.dumps(list(r.flags))
        prefixes = json.dumps(list(r.value_prefixes))
        lines.append(
            f'  {{ id: {json.dumps(r.id)}, hint: {json.dumps(r.hint, ensure_ascii=False)}, '
            f'matcher: {json.dumps(r.matcher)}, tokens: {tokens}, flags: {flags}, '
            f'value_prefixes: {prefixes} }},'
        )
    return "\n".join(lines)


def render_guard_ts(
    deny: tuple[GuardRule, ...] = OMP_GUARD_DENY_RULES,
    ask: tuple[GuardRule, ...] = OMP_GUARD_ASK_RULES,
    *,
    marker_dir: str | None = None,
) -> str:
    """The full generated ``rig-permissions-guard.ts`` content (deterministic per inputs).

    ``marker_dir`` bakes the install dir into the file for the incompatible-marker path
    (rig knows where it installed the guard — including PI_* override roots); when absent
    the generated file falls back to ``import.meta.dir`` at runtime."""
    sha = hashlib.sha256(_rules_payload(deny, ask).encode("utf-8")).hexdigest()[:16]
    provenance = json.dumps({
        "template": GUARD_TEMPLATE_VERSION,
        "sha256": sha,
        "deny": [r.id for r in deny],
        "ask": [r.id for r in ask],
    })
    return (
        _TS_TEMPLATE
        .replace("%%PROVENANCE%%", provenance)
        .replace("%%DENY_RULES%%", _rules_ts(deny))
        .replace("%%ASK_RULES%%", _rules_ts(ask))
        .replace("%%MARKER%%", INCOMPATIBLE_MARKER_NAME)
        .replace("%%MARKER_DIR%%", json.dumps(marker_dir or ""))
    )


# The generated extension, as a PLAIN string (no f-string — the TS is brace-dense).
# Placeholders: %%PROVENANCE%% (header JSON), %%DENY_RULES%% / %%ASK_RULES%% (rule table
# lines), %%MARKER%% (the incompatible-marker filename).
_TS_TEMPLATE = r"""// rig-managed permissions guard — GENERATED by rig (https://github.com/alex-mextner/rig-cli); do not edit.
// rig-guard-provenance: %%PROVENANCE%%
// Wholly rig-owned: hand edits are backed up and replaced on the next `rig apply`.
// deny rules block outright; ask rules confirm-gate via the harness UI and BLOCK headless
// (a prompt nobody can answer must never auto-approve). Reasons carry rule ids + static
// hints only — never command contents (commands can hold secrets).

interface Rule { id: string; hint: string; matcher: string; tokens: string[]; flags: string[]; value_prefixes?: string[]; }

const DENY: Rule[] = [
%%DENY_RULES%%
];
const ASK: Rule[] = [
%%ASK_RULES%%
];

// Quote-aware tokenizer: single/double quotes group, backslash escapes outside single
// quotes. Shell stage operators (&&, ||, |, ;, &, |&) split EVEN UNSPACED — a real shell
// parses `git push --force&&true` as two stages, so the guard must too. An unquoted `#`
// at a word start opens a comment through end-of-line — the shell never sees
// `echo ok # note; git reset --hard`'s "second stage", so the guard must not either.
const OPS = new Set(["&&", "||", "|", ";", "&", "|&"]);
function tokenize(command: string): string[] {
  const out: string[] = [];
  let cur = "";
  let quote = "";
  let has = false;
  const flush = () => { if (has) { out.push(cur); cur = ""; has = false; } };
  for (let i = 0; i < command.length; i++) {
    const c = command[i];
    if (quote === "") {
      if (c === "'" || c === '"') { quote = c; has = true; continue; }
      if (c === "\\" && i + 1 < command.length && command[i + 1] === "\n") { i++; continue; } // line continuation: bash removes it pre-tokenization
      if (c === "\\" && i + 1 < command.length) { cur += command[++i]; has = true; continue; }
      if (c === "#" && !has) { // comment: skip through (not including) the newline
        while (i + 1 < command.length && command[i + 1] !== "\n") i++;
        continue;
      }
      if (c === "\n") { flush(); out.push(";"); continue; } // a newline is a command separator too
      if (c === ">" || c === "<") { // redirections end a token: git push --force>/dev/null still matches
        flush();
        if (c === ">" && command[i + 1] === ">") { out.push(">>"); i++; }
        else out.push(c);
        continue;
      }
      if (c === "&" || c === "|" || c === ";") {
        flush();
        let op = c;
        if (c === "&" && command[i + 1] === "&") { op = "&&"; i++; }
        else if (c === "|" && command[i + 1] === "|") { op = "||"; i++; }
        else if (c === "|" && command[i + 1] === "&") { op = "|&"; i++; }
        out.push(op);
        continue;
      }
      if (/\s/.test(c)) { flush(); continue; }
      cur += c; has = true;
    } else if (quote === "'") {
      if (c === "'") quote = ""; else cur += c;
    } else {
      if (c === '"') quote = "";
      else if (c === "\\" && i + 1 < command.length && '"\\$`'.includes(command[i + 1])) cur += command[++i];
      else cur += c;
    }
  }
  flush();
  return out;
}

// A standalone shell operator begins a fresh pipeline stage; each stage is matched
// independently (a && b checks both).
function stages(argv: string[]): string[][] {
  const out: string[][] = [];
  let cur: string[] = [];
  for (const tok of argv) {
    if (OPS.has(tok)) { if (cur.length) out.push(cur); cur = []; }
    else cur.push(tok);
  }
  if (cur.length) out.push(cur);
  return out;
}

// Leading VAR=val env assignments are transparent to matching (FOO=1 gh pr merge still
// matches the gh-pr-merge prefix).
function stripEnv(stage: string[]): string[] {
  let i = 0;
  while (i < stage.length && /^[^\s=/][^\s=]*=/.test(stage[i])) i++;
  return stage.slice(i);
}

// Global options of git/sudo are transparent too: `git -C /repo push --force`,
// `git --no-pager push -f`, `sudo -E rm`, `sudo -u root rm` must still match. Value-taking
// globals skip TWO tokens, boolean globals one. Only applied to the programs listed.
const GLOBAL_OPTS_WITH_VALUE: Record<string, Set<string>> = {
  git: new Set(["-C", "-c", "--git-dir", "--work-tree", "--namespace"]),
  gh: new Set(["-R", "--repo", "--hostname"]),
  sudo: new Set(["-u", "-g", "-h", "-p", "-C", "-T", "-r", "-t",
                 "--user", "--group", "--host", "--prompt", "--role", "--type", "--preserve-env"]),
  env: new Set(["-u", "-C", "-S"]),
  timeout: new Set(["-k", "--kill-after", "-s", "--signal"]),
  nice: new Set(["-n", "--adjustment"]),
};
// wrappers whose FIRST operand is a value, not the command (timeout 5 git push --force)
const LEADING_VALUE_WRAPPER = new Set(["timeout"]);
const GLOBAL_OPTS_BOOL: Record<string, Set<string>> = {
  git: new Set(["-P", "--no-pager", "--literal-pathspecs", "--no-optional-locks"]),
  sudo: new Set(["-E", "-n", "-s", "-H", "-k", "-K", "-v", "-l", "-b", "-i", "--preserve-env", "--"]),
  env: new Set(["-i", "-0"]),
  command: new Set(["-p"]), // `command -p x` still runs x; -v/-V only probe (never matched)
};
// `env`/`command` execute their argument — they are transparent prefixes, not wrappers
// (unlike `sh -c`, which hides a whole new command string: the documented gap).
const TRANSPARENT_PREFIX = new Set(["env", "command", "timeout", "nice", "nohup"]);
// skip a program's global options starting at index i; returns the first operand index.
function skipOpts(stage: string[], i: number, withValue?: Set<string>, bools?: Set<string>): number {
  while (i < stage.length) {
    const tok = stage[i];
    if (withValue && withValue.has(tok)) { i += 2; continue; }
    // joined --flag=value form skips ONE token
    const eq = tok.indexOf("=");
    if (eq > 0 && withValue && withValue.has(tok.slice(0, eq))) { i += 1; continue; }
    if (bools && bools.has(tok)) { i += 1; continue; }
    break;
  }
  return i;
}

function stripGlobalOpts(stage: string[]): string[] {
  const program = stage[0];
  if (TRANSPARENT_PREFIX.has(program)) {
    // drop the prefix AND its own options (and a leading value operand for timeout), then
    // re-strip env assignments (env -i VAR=x git push --force / timeout 5 git push --force)
    let i = skipOpts(stage, 1, GLOBAL_OPTS_WITH_VALUE[program], GLOBAL_OPTS_BOOL[program]);
    if (LEADING_VALUE_WRAPPER.has(program)) i++;
    const rest = stripEnv(stage.slice(i));
    if (!rest.length) return stage;
    return stripGlobalOpts(rest);
  }
  const withValue = GLOBAL_OPTS_WITH_VALUE[program];
  const bools = GLOBAL_OPTS_BOOL[program];
  if (!withValue && !bools) return stage;
  const i = skipOpts(stage, 1, withValue, bools);
  return [program, ...stage.slice(i)];
}

function matches(rule: Rule, rawStage: string[]): boolean {
  const envStripped = stripEnv(rawStage);
  if (rule.matcher === "flag_value_prefix") {
    // PRE-strip: global-option stripping would delete the very -c payload this rule catches
    const stage = envStripped;
    // any of the flag tokens whose FOLLOWING token starts with a value prefix
    if (stage[0] !== rule.tokens[0]) return false;
    for (let i = 1; i < stage.length - 1; i++) {
      if (rule.flags.includes(stage[i]) && (rule.value_prefixes ?? []).some((p) => stage[i + 1].startsWith(p))) {
        return true;
      }
    }
    return false;
  }
  const stage = stripGlobalOpts(envStripped);
  if (rule.matcher === "argv_prefix") {
    if (stage.length < rule.tokens.length) return false;
    return rule.tokens.every((t, i) => stage[i] === t);
  }
  // subcommand_flags: program + subcommand lead the stage; at least one flag present as an
  // EXACT token anywhere (so --force-with-lease never satisfies --force).
  if (stage[0] !== rule.tokens[0] || stage[1] !== rule.tokens[1]) return false;
  return rule.flags.some((f) => stage.includes(f));
}

// The incompatible marker lives NEXT TO THIS FILE (import.meta.dir), so it lands wherever
// rig actually installed the guard — including PI_CODING_AGENT_DIR / PI_CONFIG_DIR roots —
// which is exactly where rig's drift check looks for it.
const MARKER = "%%MARKER%%";
// The install dir is BAKED at render time (rig resolved it, honoring PI_* overrides); the
// import.meta.dir / HOME forms are fallbacks for a hand-copied file only.
const BAKED_DIR = %%MARKER_DIR%%;
function markerDir(): string {
  if (BAKED_DIR) return BAKED_DIR;
  const anyMeta: any = import.meta;
  if (anyMeta && typeof anyMeta.dir === "string") return anyMeta.dir;
  return (process.env.HOME ?? ".") + "/.omp/agent/extensions";
}
async function writeMarker(why: string): Promise<void> {
  try {
    const fs = await import("node:fs");
    const path = await import("node:path");
    fs.writeFileSync(path.join(markerDir(), MARKER), "rig guard incompatible: " + why + " — blocking fail-closed; re-run `rig apply`\n");
  } catch { /* best effort — the block decision is the enforcement */ }
}
async function clearMarker(): Promise<void> {
  try {
    const fs = await import("node:fs");
    const path = await import("node:path");
    fs.rmSync(path.join(markerDir(), MARKER), { force: true });
  } catch { /* best effort */ }
}

export default function (pi: any) {
  pi.setLabel("rig permissions guard");

  // Positive heartbeat: the guard only fires on a tool NAMED "bash" — if omp renamed the
  // tool, no per-event check can see it, so verify the registry once per session and drop
  // the loud marker rig status surfaces (and clear a stale one when healthy again).
  pi.on("session_start", async (_event: any, ctx: any) => {
    try {
      const tools = typeof pi.getAllTools === "function" ? pi.getAllTools() : [];
      const names = new Set((tools ?? []).map((t: any) => t && t.name));
      if (names.size > 0 && !names.has("bash")) {
        // a bash-LESS registry is NOT incompatible: restricted toolsets are legitimate (no
        // shell exists to guard). Notify only — the per-call fail-closed checks below cover
        // a renamed toolName field; writing the marker here would flag restricted profiles
        // as permanent false-positive drift.
        if (ctx.hasUI && ctx.ui && typeof ctx.ui.notify === "function") {
          ctx.ui.notify("rig guard: no 'bash' tool in this session — nothing to guard", "info");
        }
      }
      // no clearMarker here: a session_start heartbeat can't contradict a tool_call shape
      // failure — only the tool_call path below clears (and rig apply is the operator path).
    } catch { /* registry probe failed — the per-call checks below still apply */ }
  });

  pi.on("tool_call", async (event: any, ctx: any) => {
    // Runtime event-shape self-check, BEFORE the fast path: if omp dropped the toolName
    // field, fail CLOSED (block + loud marker) instead of silently enforcing nothing.
    if (typeof event.toolName !== "string") {
      await writeMarker("tool_call event shape changed: toolName is not a string");
      return { block: true, reason: "rig guard: incompatible omp event shape (toolName) — blocking fail-closed until `rig apply` regenerates" };
    }
    if (event.toolName !== "bash") return; // fast-path: only shell commands are guarded
    const input = event.input;
    if (!input || typeof input.command !== "string") {
      await writeMarker("tool_call event shape changed: input.command is not a string");
      return { block: true, reason: "rig guard: incompatible omp event shape (input.command) — blocking fail-closed until `rig apply` regenerates" };
    }
    await clearMarker(); // a healthy shape check is the evidence that contradicts the marker
    for (const stage of stages(tokenize(input.command))) {
      for (const rule of DENY) {
        if (matches(rule, stage)) {
          return { block: true, reason: "rig guard deny " + rule.id + ": " + rule.hint };
        }
      }
      for (const rule of ASK) {
        if (!matches(rule, stage)) continue;
        if (ctx.hasUI && ctx.ui && typeof ctx.ui.confirm === "function") {
          const ok = await ctx.ui.confirm("rig guard", rule.hint + "\n\nAllow this command?");
          if (!ok) return { block: true, reason: "rig guard ask " + rule.id + " (rejected): " + rule.hint };
          // confirmed — keep scanning the remaining stages (a later one may still deny)
        } else {
          return { block: true, reason: "rig guard ask " + rule.id + " (headless — no confirm UI): " + rule.hint };
        }
      }
    }
  });
}
"""


def guard_provenance(content: str) -> dict | None:
    """Parse the provenance header back out of a generated file. ``None`` for a foreign file."""
    for line in content.splitlines()[:5]:
        if line.startswith(_PROVENANCE_PREFIX):
            try:
                prov = json.loads(line[len(_PROVENANCE_PREFIX):])
            except json.JSONDecodeError:
                return None
            return prov if isinstance(prov, dict) and "template" in prov else None
    return None
